"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from firebase_admin import initialize_app
from decouple import config
from celery.schedules import crontab



FIREBASE_APP = initialize_app()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
GEMINI_API_KEY = config('GEMINI_API_KEY')
DB_PASSWORD = config('DB_PASSWORD')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['junstock.duckdns.org', 'www.junstock.duckdns.org', 'localhost', '127.0.0.1', '192.168.0.174']

if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',  

    # 서드파티 라이브러리
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken', # dj-rest-auth에 필요
    'rest_framework_simplejwt.token_blacklist', 
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'django_celery_beat',

    'allauth', # dj-rest-auth에 필요
    'allauth.account',
    'allauth.socialaccount',
    'fcm_django',

    'debug_toolbar',
    'django_extensions',
    'django_htmx',
    'widget_tweaks',

    'stocks.apps.StocksConfig', # 또는 간단히 'stocks'라고 적어도 됩니다.
    'core',
    'users',
    
]

AUTH_USER_MODEL = 'stocks.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_stocks', # user_stocks 함수가 위치한 경로 추가

            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# if DEBUG:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'stock_app_db',
        'USER': 'jun',
        'PASSWORD': DB_PASSWORD, 
        'HOST': 'db',
        'PORT': '5432',
    }
}
# else:
#     # 데이터베이스 설정을 PostgreSQL로 변경
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'stock_app_db',
#             'USER': 'jun',
#             'PASSWORD': DB_PASSWORD,
#             'HOST': 'localhost',
#             'PORT': '5432',
#         }
#     }

# ALTER DATABASE stock_app_db OWNER TO stock_app_user;
# sudo -u postgres pg_dump stock_app_db > db_backup.sql
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # 기본 인증 방식을 JWT로 설정
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 기본 권한 정책 (인증된 사용자만 접근 가능하도록 설정할 수 있음)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

}


# JWT 사용 설정
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False, # Flutter에서 토큰을 사용하기 위해 False로 설정
    'USER_DETAILS_SERIALIZER': 'stocks.serializers.UserSerializer',
}

# Celery Settings
CELERY_BROKER_URL = 'redis://redis:6379/0'  # Redis 서버 주소
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul' # 시간대 설정

FCM_DJANGO_SETTINGS = {
    # 이 부분은 True로 설정해야 FCMDevice 모델의 user 필드를 ForeignKey로 사용할 수 있습니다.
    "FCM_DEVICE_MODEL": "fcm_django.FCMDevice", 
    "APP_VERBOSE_NAME": "Stock App",
    # 다운로드한 서비스 계정 키 파일의 경로
    "FCM_SERVER_KEY": os.path.join(BASE_DIR, 'fcm-service-account-key.json'),
}


# ⚡️ SMTP 백엔드로 변경
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# --- Gmail SMTP 서버 정보 ---
EMAIL_HOST = 'smtp.gmail.com'         # Gmail SMTP 서버 주소
EMAIL_PORT = 587                      # Gmail SMTP 포트 번호
EMAIL_HOST_USER = config('EMAIL_HOST_USER') # ⚡️ 당신의 Gmail 주소
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD') # ⚡️ 위에서 발급받은 16자리 앱 비밀번호
EMAIL_USE_TLS = True                  # TLS(전송 계층 보안) 사용
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 발신자 이메일 주소 (위와 동일하게)

ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional' # 'mandatory'로 하면 인증 메일을 보내야만 로그인이 됨. 'optional'이나 'none'으로 설정.
ACCOUNT_UNIQUE_EMAIL = True        # 모든 사용자의 이메일은 유일해야 함

ACCOUNT_FORMS = {
    'login': 'users.forms.CustomLoginForm',
    'signup': 'users.forms.CustomSignupForm',
    # 'add_email': 'allauth.account.forms.AddEmailForm',
    # 'change_password': 'allauth.account.forms.ChangePasswordForm',
    # 'set_password': 'allauth.account.forms.SetPasswordForm',
    # 'reset_password': 'allauth.account.forms.ResetPasswordForm',
    # 'reset_password_from_key': 'allauth.account.forms.ResetPasswordKeyForm',
    # 'disconnect': 'allauth.socialaccount.forms.DisconnectForm',
}

# ACCOUNT_USERNAME_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD
# ACCOUNT_EMAIL_REQUIRED

# 정적 파일(Static files) 설정
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # 배포 시 정적 파일들이 모일 폴더


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1", # ⚡️ Celery와 다른 DB 번호(1) 사용
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = '/mnt/movies'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',  # DEBUG, INFO, WARNING, ERROR, CRITICAL
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'

CELERY_BEAT_SCHEDULE = {
    # 1. 매일 아침 주식 데이터 동기화 (미국장 마감 후 오전 8시)
    'sync-stocks-every-morning': {
        'task': 'stocks.tasks.sync_all_stocks_data', # 실제 경로에 맞춰 수정
        'schedule': crontab(hour=8, minute=0),
    },
    # 2. 대시보드 데이터 업데이트 (5분마다)
    'update-dashboard-5min': {
        'task': 'stocks.tasks.update_dashboard_task',
        'schedule': crontab(minute='*/5'),
    },
    # 3. AI 주가 예측 실행 (데이터 동기화 후 오전 8시 30분)
    # pytorch_queue를 사용하도록 설정된 경우 자동으로 해당 워커가 가져감
    'run-ai-predictions-daily': {
        'task': 'stocks.tasks.run_daily_predictions',
        'schedule': crontab(hour=8, minute=30),
        'options': {'queue': 'pytorch_queue'} 
    },
    # 4. 일일 리포트 생성 및 이메일 발송 (오전 9시)
    'send-daily-reports': {
        'task': 'stocks.tasks.schedule_all_daily_reports',
        'schedule': crontab(hour=9, minute=0),
    },
    # 5. 목표가 도달 알림 체크 (장중 1분마다)
    'check-target-prices': {
        'task': 'stocks.tasks.check_stock_prices_and_notify',
        'schedule': crontab(minute='*'),
    },
    # 6. 예측 결과 평가 (새벽 2시)
    'evaluate-ai-performance': {
        'task': 'stocks.tasks.evaluate_predictions',
        'schedule': crontab(hour=2, minute=0),
    },
}