# Generated by Django 5.2.4 on 2025-07-31 12:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import stocks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('key', models.CharField(default='main_dashboard', max_length=50, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '대시보드 데이터',
                'verbose_name_plural': '대시보드 데이터',
            },
        ),
        migrations.CreateModel(
            name='FinancialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yfinance_name', models.CharField(max_length=255, unique=True, verbose_name='yfinance 계정과목명')),
                ('standard_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='표준 키')),
                ('korean_label', models.CharField(blank=True, max_length=100, verbose_name='한글 라벨')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='종목코드')),
                ('short_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='종목명 (단축)')),
                ('long_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='종목명 (전체)')),
                ('market', models.CharField(blank=True, max_length=50, null=True, verbose_name='시장')),
                ('is_sp500', models.BooleanField(default=False, verbose_name='S&P 500 포함 여부')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='현재가')),
                ('market_change', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='변동액')),
                ('change_percent', models.FloatField(blank=True, null=True, verbose_name='변동률 (%)')),
                ('day_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='금일 고가')),
                ('day_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='금일 저가')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='거래량')),
                ('market_cap', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='시가총액')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='섹터')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='산업')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='웹사이트')),
                ('long_business_summary', models.TextField(blank=True, null=True, verbose_name='기업 개요')),
                ('full_time_employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='직원 수')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='도시')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='주')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='국가')),
                ('trailing_eps', models.FloatField(blank=True, null=True, verbose_name='EPS (Trailing)')),
                ('forward_eps', models.FloatField(blank=True, null=True, verbose_name='EPS (Forward)')),
                ('trailing_pe', models.FloatField(blank=True, null=True, verbose_name='PER (Trailing)')),
                ('forward_pe', models.FloatField(blank=True, null=True, verbose_name='PER (Forward)')),
                ('price_to_book', models.FloatField(blank=True, null=True, verbose_name='PBR')),
                ('dividend_yield', models.FloatField(blank=True, null=True, verbose_name='배당수익률 (%)')),
                ('fifty_two_week_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='52주 최고가')),
                ('fifty_two_week_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='52주 최저가')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화 시간')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ai_credit', models.IntegerField(default=10, verbose_name='AI 리포트 크레딧')),
                ('profile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=stocks.models.generate_reset_code, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='뉴스 제목')),
                ('description', models.TextField(default='', verbose_name='뉴스 요약')),
                ('url', models.CharField(default='', max_length=500, verbose_name='링크')),
                ('thumbnail', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='썸네일')),
                ('published_at', models.DateTimeField(verbose_name='발행일')),
                ('related_stocks', models.ManyToManyField(blank=True, related_name='news', to='stocks.stock', verbose_name='관련 종목')),
            ],
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(verbose_name='AI 리포트 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 업데이트일')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='UserReportViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='목표가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='stocks.stock', verbose_name='주식')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
