# stocks/migrations/000X_populate_financial_items.py

from django.db import migrations

# 데이터베이스에 저장할 계정과목 목록 (완전판)
# {'yfinance_name': (standard_key, korean_label)} 형식
FINANCIAL_ITEMS_DATA = {
    'Accrued Interest Receivable': ('accrued_interest_receivable', '미수이자'),
    'Amortization Of Intangibles': ('amortization_of_intangibles', '무형자산상각'),
    'Amortization Of Securities': ('amortization_of_securities', '유가증권상각'),
    'Asset Impairment Charge': ('asset_impairment_charge', '자산손상차손'),
    'Assets Held For Sale Current': ('assets_held_for_sale_current', '매각예정유동자산'),
    'Available For Sale Securities': ('available_for_sale_securities', '매도가능증권'),
    'Average Dilution Earnings': ('average_dilution_earnings', '평균 희석이익'),
    'Capital Lease Obligations': ('capital_lease_obligations', '금융리스부채'),
    'Capital Stock': ('capital_stock', '자본금'),
    'Cash Cash Equivalents And Federal Funds Sold': ('cash_and_equivalents', '현금및현금성자산'),
    'Cash Equivalents': ('cash_equivalents', '현금성자산'),
    'Cash Financial': ('cash_financial', '재무현금'),
    'Cash Flow From Discontinued Operation': ('cash_flow_discontinued_ops', '중단사업 현금흐름'),
    'Cash From Discontinued Financing Activities': ('cash_from_discontinued_financing', '중단사업 재무활동 현금'),
    'Cash From Discontinued Investing Activities': ('cash_from_discontinued_investing', '중단사업 투자활동 현금'),
    'Cash From Discontinued Operating Activities': ('cash_from_discontinued_operating', '중단사업 영업활동 현금'),
    'Cash Flowsfromusedin Operating Activities Direct': ('operating_cash_flow_direct', '영업활동 현금흐름(직접법)'),
    'Change In Account Payable': ('change_in_payables', '매입채무 증감'),
    'Change In Accrued Expense': ('change_in_accrued_expense', '미지급비용 증감'),
    'Change In Dividend Payable': ('change_in_dividend_payable', '미지급배당금 증감'),
    'Change In Income Tax Payable': ('change_in_income_tax_payable', '미지급법인세 증감'),
    'Change In Interest Payable': ('change_in_interest_payable', '미지급이자 증감'),
    'Change In Other Current Assets': ('change_in_other_current_assets', '기타유동자산 증감'),
    'Change In Other Current Liabilities': ('change_in_other_current_liabilities', '기타유동부채 증감'),
    'Change In Other Working Capital': ('change_in_other_working_capital', '기타운전자본 증감'),
    'Change In Prepaid Assets': ('change_in_prepaid_assets', '선급자산 증감'),
    'Change In Tax Payable': ('change_in_tax_payable', '미지급세금 증감'),
    'Changes In Account Receivables': ('change_in_receivables', '매출채권 증감'),
    'Classesof Cash Payments': ('classes_of_cash_payments', '현금지출 분류'),
    'Classesof Cash Receiptsfrom Operating Activities': ('classes_of_cash_receipts_operating', '영업활동 현금수령 분류'),
    'Commercial Paper': ('commercial_paper', '기업어음'),
    'Common Stock Payments': ('common_stock_payments', '보통주 지급'),
    'Construction In Progress': ('construction_in_progress', '건설중인자산'),
    'Current Accrued Expenses': ('current_accrued_expenses', '유동 미지급비용'),
    'Current Capital Lease Obligation': ('current_capital_lease_obligation', '유동금융리스부채'),
    'Current Debt And Capital Lease Obligation': ('current_debt_and_lease', '유동부채 및 리스부채'),
    'Current Deferred Assets': ('current_deferred_assets', '유동이연자산'),
    'Current Deferred Liabilities': ('current_deferred_liabilities', '유동이연부채'),
    'Current Deferred Taxes Assets': ('current_deferred_tax_assets', '유동이연법인세자산'),
    'Current Deferred Taxes Liabilities': ('current_deferred_tax_liabilities', '유동이연법인세부채'),
    'Current Notes Payable': ('current_notes_payable', '유동지급어음'),
    'Current Provisions': ('current_provisions', '유동충당부채'),
    'Defined Pension Benefit': ('defined_pension_benefit', '확정급여형 퇴직연금'),
    'Depletion': ('depletion', '감모상각비'),
    'Depletion Income Statement': ('depletion_is', '감모상각비 (손익계산서)'),
    'Depreciation Amortization Depletion': ('depreciation_amortization_depletion', '감가상각 및 감모상각비'),
    'Derivative Product Liabilities': ('derivative_product_liabilities', '파생상품부채'),
    'Diluted NI Availto Com Stockholders': ('diluted_ni_for_common', '희석 보통주 귀속순이익'),
    'Dividend Received Cfo': ('dividend_received_operating', '배당금 수령 (영업활동)'),
    'Dividends Paid Direct': ('dividend_paid', '배당금 지급'),
    'Dividends Received Cfi': ('dividend_received_investing', '이자 수령 (투자활동)'),
    'Dividends Received Direct': ('dividend_received', '배당금 수령'),
    'Duefrom Related Parties Current': ('due_from_related_parties_current', '유동 특수관계자 미수금'),
    'Duefrom Related Parties Non Current': ('due_from_related_parties_non_current', '비유동 특수관계자 미수금'),
    'Dueto Related Parties Current': ('due_to_related_parties_current', '유동 특수관계자 미지급금'),
    'Dueto Related Parties Non Current': ('due_to_related_parties_non_current', '비유동 특수관계자 미지급금'),
    'Employee Benefits': ('employee_benefits', '종업원급여'),
    'Excess Tax Benefit From Stock Based Compensation': ('tax_benefit_stock_compensation', '주식보상 초과세금혜택'),
    'Excise Taxes': ('excise_taxes', '소비세'),
    'Financial Assets Designatedas Fair Value Through Profitor Loss Total': ('financial_assets_fvtpl', '당기손익-공정가치측정금융자산'),
    'Fixed Assets Revaluation Reserve': ('fixed_assets_revaluation_reserve', '고정자산 재평가적립금'),
    'Foreign Currency Translation Adjustments': ('foreign_currency_translation_adj', '외화환산조정'),
    'Gain Loss On Investment Securities': ('gain_loss_investment_securities', '투자증권 처분손익'),
    'Gain Loss On Sale Of PPE': ('gain_loss_on_sale_ppe', '유형자산 처분손익'),
    'Gain On Sale Of Business': ('gain_on_sale_of_business', '사업 매각 이익'),
    'Gain On Sale Of Ppe': ('gain_loss_on_sale_ppe', '유형자산 처분손익'),
    'Gain On Sale Of Security': ('gain_on_sale_of_security', '유가증권 처분이익'),
    'General Partnership Capital': ('general_partnership_capital', '일반조합 자본금'),
    'Held To Maturity Securities': ('held_to_maturity_securities', '만기보유증권'),
    'Hedging Assets Current': ('hedging_assets_current', '유동 위험회피자산'),
    'Impairment Of Capital Assets': ('impairment_of_capital_assets', '자본자산 손상'),
    'Income Tax Paid Supplemental Data': ('income_tax_paid', '법인세 납부액'),
    'Income Tax Payable': ('income_tax_payable', '미지급법인세'),
    'Insurance And Claims': ('insurance_and_claims', '보험 및 청구'),
    'Interest Paid Cff': ('interest_paid_financing', '이자 지급 (재무활동)'),
    'Interest Paid Direct': ('interest_paid', '이자 지급'),
    'Interest Paid Supplemental Data': ('interest_paid_supplemental', '이자 지급 (보충자료)'),
    'Interest Payable': ('interest_payable', '미지급이자'),
    'Interest Received Cfi': ('interest_received_investing', '이자 수령 (투자활동)'),
    'Interest Received Cfo': ('interest_received_operating', '이자 수령 (영업활동)'),
    'Interest Received Direct': ('interest_received', '이자 수령'),
    'Inventories Adjustments Allowances': ('inventory_adjustments', '재고자산 평가충당금'),
    'Investment Properties': ('investment_properties', '투자부동산'),
    'Investments In Other Ventures Under Equity Method': ('investments_in_associates', '관계기업 투자'),
    'Investmentsin Associatesat Cost': ('investments_in_associates', '관계기업 투자'),
    'Investmentsin Joint Venturesat Cost': ('investments_in_joint_ventures', '공동기업 투자'),
    'Investmentsin Subsidiariesat Cost': ('investments_in_subsidiaries', '종속기업 투자'),
    'Issuance Of Capital Stock': ('issuance_of_capital_stock', '자본금 발행'),
    'Issuance Of Debt': ('issuance_of_debt', '부채 발행'),
    'Leases': ('lease_assets', '리스자산'),
    'Liabilities Heldfor Sale Non Current': ('liabilities_held_for_sale_non_current', '매각예정비유동부채'),
    'Limited Partnership Capital': ('limited_partnership_capital', '유한조합 자본금'),
    'Line Of Credit': ('line_of_credit', '신용한도'),
    'Loans Receivable': ('loans_receivable', '대여금'),
    'Long Term Capital Lease Obligation': ('long_term_capital_lease_obligation', '장기금융리스부채'),
    'Long Term Debt Issuance': ('long_term_debt_issuance', '장기부채 발행액'),
    'Long Term Debt Payments': ('long_term_debt_payments', '장기부채 상환'),
    'Long Term Equity Investment': ('long_term_equity_investment', '장기지분투자'),
    'Long Term Provisions': ('long_term_provisions', '장기충당부채'),
    'Loss Adjustment Expense': ('loss_adjustment_expense', '손실조정비용'),
    'Minimum Pension Liabilities': ('minimum_pension_liabilities', '최소퇴직연금부채'),
    'Minority Interest': ('minority_interest', '비지배지분'),
    'Net Business Purchase And Sale': ('net_business_purchase_sale', '사업 순매수/매도'),
    'Net Income Extraordinary': ('net_income_extraordinary', '특별손익'),
    'Net Income From Tax Loss Carryforward': ('net_income_from_tax_loss_carryforward', '세무상결손금 이월순이익'),
    'Net Intangibles Purchase And Sale': ('net_intangibles_purchase_sale', '무형자산 순매수/매도'),
    'Net Investment Purchase And Sale': ('net_investment_purchase_sale', '투자자산 순매수/매도'),
    'Net Long Term Debt Issuance': ('net_long_term_debt_issuance', '장기부채 순발행액'),
    'Net Other Financing Charges': ('net_other_financing_charges', '순기타재무비용'),
    'Net Other Investing Changes': ('net_other_investing_changes', '순기타투자변동'),
    'Net Policyholder Benefits And Claims': ('net_policyholder_benefits_claims', '순보험계약자혜택 및 청구'),
    'Net Preferred Stock Issuance': ('net_preferred_stock_issuance', '우선주 순발행액'),
    'Net Short Term Debt Issuance': ('net_short_term_debt_issuance', '단기부채 순발행액'),
    'Net Tangible Assets': ('net_tangible_assets', '순유형자산'),
    'Non Current Accounts Receivable': ('non_current_accounts_receivable', '비유동매출채권'),
    'Non Current Accrued Expenses': ('non_current_accrued_expenses', '비유동미지급비용'),
    'Non Current Deferred Assets': ('non_current_deferred_assets', '비유동이연자산'),
    'Non Current Deferred Liabilities': ('non_current_deferred_liabilities', '비유동이연부채'),
    'Non Current Deferred Revenue': ('non_current_deferred_revenue', '비유동이연수익'),
    'Non Current Deferred Taxes Assets': ('non_current_deferred_tax_assets', '비유동이연법인세자산'),
    'Non Current Deferred Taxes Liabilities': ('non_current_deferred_tax_liabilities', '비유동이연법인세부채'),
    'Non Current Note Receivables': ('non_current_note_receivables', '비유동받을어음'),
    'Non Current Pension And Other Postretirement Benefit Plans' : ('non_current_pension_benefits', '비유동 퇴직연금 및 기타 퇴직후급여'),
    'Non Current Prepaid Assets' : ('non_current_prepaid_assets', '비유동선급자산'),
    'Notes Receivable' : ('notes_receivable', '받을어음'),
    'Occupancy And Equipment' : ('occupancy_and_equipment', '점유 및 장비 비용'),
    'Ordinary Shares Number' : ('ordinary_shares_number', '보통주 주식수'),
    'Other Cash Adjustment Inside Changein Cash' : ('other_cash_adjustment_inside', '기타 현금 조정 (내부)'),
    'Other Cash Adjustment Outside Changein Cash' : ('other_cash_adjustment_outside', '기타 현금 조정 (외부)'),
    'Other Cash Paymentsfrom Operating Activities' : ('other_cash_payments_operating', '기타 영업활동 현금지출'),
    'Other Cash Receiptsfrom Operating Activities' : ('other_cash_receipts_operating', '기타 영업활동 현금수령'),
    'Other Current Assets' : ('other_current_assets', '기타유동자산'),
    'Other Current Borrowings' : ('other_current_borrowings', '기타유동차입금'),
    'Other Current Liabilities' : ('other_current_liabilities', '기타유동부채'),
    'Other Equity Interest' : ('other_equity_interest', '기타지분'),
    'Other Investments' : ('other_investments', '기타 투자자산'),
    'Other Non Cash Items' : ('other_non_cash_items', '기타비현금항목'),
    'Other Non Current Assets' : ('other_non_current_assets', '기타비유동자산'),
    'Other Non Current Liabilities' : ('other_non_current_liabilities', '기타비유동부채'),
    'Other Non Interest Expense' : ('other_non_interest_expense', '기타비이자비용'),
    'Other Payable' : ('other_payable', '기타미지급금'),
    'Other Properties' : ('other_properties', '기타부동산'),
    'Other Special Charges' : ('other_special_charges', '기타특별비용'),
    'Other Taxes' : ('other_taxes', '기타세금'),
    'Otherunder Preferred Stock Dividend' : ('other_under_preferred_dividend', '기타 우선주 배당금 관련'),
    'Paymentson Behalfof Employees' : ('payments_for_employees', '종업원을 위한 지급'),
    'Paymentsto Suppliersfor Goodsand Services' : ('payments_to_suppliers', '공급업체 대금지급'),
    'Pension And Employee Benefit Expense' : ('pension_employee_benefit_expense', '퇴직연금 및 종업원급여 비용'),
    'Pensionand Other Post Retirement Benefit Plans Current' : ('current_pension_benefits', '유동 퇴직연금 및 기타 퇴직후급여'),
    'Policyholder Benefits Ceded' : ('policyholder_benefits_ceded', '출재보험 계약자혜택'),
    'Policyholder Benefits Gross' : ('policyholder_benefits_gross', '총 보험계약자혜택'),
    'Preferred Shares Number' : ('preferred_shares_number', '우선주 주식수'),
    'Preferred Securities Outside Stock Equity' : ('preferred_securities_outside_equity', '자본 외 우선증권'),
    'Preferred Stock' : ('preferred_stock', '우선주'),

    'Preferred Stock Dividend Paid': ('preferred_dividend_paid', '우선주 배당금 지급'),
    'Preferred Stock Dividends' : ('preferred_stock_dividends', '우선주 배당금'),
    'Preferred Stock Equity' : ('preferred_stock_equity', '우선주 자본'),
    'Preferred Stock Issuance' : ('preferred_stock_issuance', '우선주 발행'),
    'Preferred Stock Payments' : ('preferred_stock_payments', '우선주 지급'),
    'Proceeds From Stock Option Exercised' : ('proceeds_from_stock_options', '스톡옵션 행사 수익'),
    'Professional Expense And Contract Services Expense' : ('professional_fees', '전문용역비'),
    'Provisionand Write Offof Assets' : ('provision_and_write_off', '자산 충당금 및 상각'),
    'Purchase Of Business' : ('purchase_of_business', '사업 인수'),
    'Purchase Of Investment Properties' : ('purchase_of_investment_properties', '투자부동산 매입'),
    'Receiptsfrom Customers' : ('receipts_from_customers', '고객으로부터의 수령액'),
    'Receiptsfrom Government Grants' : ('receipts_from_gov_grants', '정부 보조금 수령'),
    'Receivables Adjustments Allowances' : ('receivables_adjustments_allowances', '매출채권 조정 및 충당금'),
    'Rent And Landing Fees' : ('rent_and_landing_fees', '임차료 및 착륙료'),
    'Rent Expense Supplemental' : ('rent_expense', '임차료'),
    'Restricted Common Stock' : ('restricted_common_stock', '제한조건부 보통주'),
    'Salaries And Wages' : ('salaries_and_wages', '급여 및 임금'),
    'Sale Of Investment Properties' : ('sale_of_investment_properties', '투자부동산 매각'),
    'Securities Amortization' : ('securities_amortization', '유가증권상각'),
    'Share Issued' : ('shares_issued', '발행주식수'),
    'Short Term Debt Issuance' : ('short_term_debt_issuance', '단기부채 발행액'),
    'Tax Effect Of Unusual Items' : ('tax_effect_unusual_items', '특별항목 법인세효과'),
    'Taxes Receivable' : ('taxes_receivable', '미수세금'),
    'Taxes Refund Paid' : ('taxes_refund_paid', '세금 환급 지급'),
    'Taxes Refund Paid Direct' : ('taxes_refund_paid', '세금 환급 지급'),
    'Total Other Finance Cost' : ('total_other_finance_cost', '총기타재무원가'),
    'Total Partnership Capital' : ('total_partnership_capital', '총조합 자본금'),
    'Total Tax Payable' : ('total_tax_payable', '총미지급세금'),
    'Tradeand Other Payables Non Current' : ('trade_other_payables_non_current', '비유동 매입채무 및 기타미지급금'),
    'Treasury Shares Number' : ('treasury_shares_number', '자기주식 주식수'),
    'Unrealized Gain Loss' : ('unrealized_gain_loss', '미실현손익'),
    'Unrealized Gain Loss On Investment Securities' : ('unrealized_gain_loss_investment_securities', '투자증권 미실현손익'),
    'Write Off' : ('write_off', '자산상각'),

    # --- 손익계산서 (Income Statement) ---
    'Total Revenue': ('total_revenue', '총 매출'),
    'Operating Revenue': ('total_revenue', '총 매출'),
    'Cost Of Revenue': ('cost_of_revenue', '매출원가'),
    'Reconciled Cost Of Revenue': ('cost_of_revenue', '매출원가'),
    'Gross Profit': ('gross_profit', '매출 총이익'),
    'Operating Income': ('operating_income', '영업이익'),
    'Total Operating Income As Reported': ('operating_income', '영업이익'),
    'Operating Expense': ('operating_expense', '영업비용'),
    'Selling General And Administration': ('sga_expense', '판매비와관리비'),
    'General And Administrative Expense': ('sga_expense', '판매비와관리비'),
    'Selling And Marketing Expense': ('sga_expense', '판매비와관리비'),
    'Other Gand A': ('sga_expense', '판매비와관리비'),
    'Research And Development': ('r_and_d', '연구개발비'),
    'Depreciation And Amortization In Income Statement': ('depreciation_amortization_is', '감가상각비 (손익계산서)'),
    'Depreciation Amortization Depletion Income Statement': ('depreciation_amortization_is', '감가상각비 (손익계산서)'),
    'Depreciation Income Statement': ('depreciation_amortization_is', '감가상각비 (손익계산서)'),
    'Amortization Of Intangibles Income Statement': ('amortization_is', '무형자산상각비 (손익계산서)'),
    'EBIT': ('ebit', 'EBIT (세전영업이익)'),
    'EBITDA': ('ebitda', 'EBITDA'),
    'Normalized EBITDA': ('normalized_ebitda', '조정 EBITDA'),
    'Net Interest Income': ('net_interest_income', '순이자손익'),
    'Interest Income': ('interest_income', '이자수익'),
    'Interest Income Non Operating': ('interest_income', '이자수익'),
    'Interest Expense': ('interest_expense', '이자비용'),
    'Interest Expense Non Operating': ('interest_expense', '이자비용'),
    'Net Non Operating Interest Income Expense': ('net_non_operating_interest_income', '순영업외이자손익'),
    'Other Income Expense': ('other_income_expense', '기타손익'),
    'Other Non Operating Income Expenses': ('other_income_expense', '기타손익'),
    'Pretax Income': ('pretax_income', '세전이익'),
    'Tax Provision': ('tax_provision', '법인세비용'),
    'Tax Rate For Calcs': ('tax_rate', '실효세율'),
    'Net Income': ('net_income', '순이익'),
    'Net Income Common Stockholders': ('net_income', '순이익'),
    'Net Income From Continuing Operations': ('net_income', '순이익'),
    'Net Income Continuous Operations': ('net_income', '순이익'),
    'Net Income Including Noncontrolling Interests': ('net_income', '순이익'),
    'Net Income From Continuing And Discontinued Operation': ('net_income', '순이익'),
    'Net Income From Continuing Operation Net Minority Interest': ('net_income', '순이익'),
    'Net Income Discontinuous Operations': ('net_income_discontinued_ops', '중단사업순이익'),
    'Normalized Income': ('normalized_income', '조정 순이익'),
    'Basic EPS': ('basic_eps', '기본 EPS'),
    'Diluted EPS': ('diluted_eps', '희석 EPS'),
    'Basic Average Shares': ('basic_avg_shares', '기본 평균주식수'),
    'Diluted Average Shares': ('diluted_avg_shares', '희석 평균주식수'),
    'Total Expenses': ('total_expenses', '총 비용'),
    'Other Operating Expenses': ('other_operating_expenses', '기타 영업비용'),
    'Earnings Losses From Equity Investments': ('gain_loss_equity_investments', '지분법 투자손익'),
    'Earnings From Equity Interest': ('gain_loss_equity_investments', '지분법 투자손익'),
    'Earnings From Equity Interest Net Of Tax': ('gain_loss_equity_investments_net_tax', '지분법 투자손익(세후)'),
    'Special Income Charges': ('special_income_charges', '특별비용'),
    'Restructuring And Mergern Acquisition': ('restructuring_expense', '구조조정 및 M&A 비용'),
    'Operating Gains Losses': ('operating_gains_losses', '영업 손익'),
    'Gain Loss On Sale Of Business': ('gain_loss_sale_of_business', '사업 매각 손익'),
    'Sale Of Business': ('sale_of_business', '사업 매각'),
    'Total Unusual Items': ('total_unusual_items', '총 특별 항목'),
    'Total Unusual Items Excluding Goodwill': ('total_unusual_items_excl_goodwill', '영업권 제외 총 특별항목'),

    # --- 재무상태표 (Balance Sheet) ---
    'Total Assets': ('total_assets', '총 자산'),
    'Current Assets': ('current_assets', '유동자산'),
    'Cash And Cash Equivalents': ('cash_and_equivalents', '현금및현금성자산'),
    'Cash Cash Equivalents And Short Term Investments': ('cash_and_equivalents', '현금및현금성자산'),
    'Cash Equivalents': ('cash_equivalents', '현금성자산'),
    'Restricted Cash': ('restricted_cash', '사용제한현금'),
    'Other Short Term Investments': ('short_term_investments', '단기투자자산'),
    'Receivables': ('receivables', '매출채권'),
    'Accounts Receivable': ('receivables', '매출채권'),
    'Gross Accounts Receivable': ('gross_receivables', '총 매출채권'),
    'Allowance For Doubtful Accounts Receivable': ('allowance_for_doubtful_accounts', '대손충당금'),
    'Provision For Doubtful Accounts': ('allowance_for_doubtful_accounts', '대손충당금'),
    'Inventory': ('inventory', '재고자산'),
    'Work In Process': ('work_in_process', '재공품'),
    'Raw Materials': ('raw_materials', '원재료'),
    'Finished Goods': ('finished_goods', '제품'),
    'Other Inventories': ('other_inventories', '기타 재고자산'),
    'Prepaid Assets': ('prepaid_assets', '선급자산'),
    'Net PPE': ('net_ppe', '순유형자산'),
    'Gross PPE': ('gross_ppe', '총유형자산'),
    'Properties': ('properties', '부동산'),
    'Land And Improvements': ('land_and_improvements', '토지 및 시설'),
    'Buildings And Improvements': ('buildings_and_improvements', '건물 및 시설'),
    'Machinery Furniture Equipment': ('machinery_and_equipment', '기계 및 장비'),
    'Accumulated Depreciation': ('accumulated_depreciation', '감가상각누계액'),
    'Total Non Current Assets': ('non_current_assets', '비유동자산'),
    'Goodwill And Other Intangible Assets': ('goodwill_and_intangibles', '영업권및무형자산'),
    'Goodwill': ('goodwill', '영업권'),
    'Other Intangible Assets': ('other_intangible_assets', '기타 무형자산'),
    'Investments And Advances': ('investments_and_advances', '장기투자자산 및 선급금'),
    'Investmentin Financial Assets': ('investment_in_financial_assets', '금융자산 투자'),
    'Financial Assets': ('financial_assets', '금융자산'),
    'Available For Sale Securities': ('available_for_sale_securities', '매도가능증권'),
    'Trading Securities': ('trading_securities', '단기매매증권'),
    'Total Liabilities Net Minority Interest': ('total_liabilities', '총 부채'),
    'Current Liabilities': ('current_liabilities', '유동부채'),
    'Payables': ('payables', '매입채무'),
    'Accounts Payable': ('payables', '매입채무'),
    'Payables And Accrued Expenses': ('payables_and_accrued_expenses', '매입채무 및 미지급비용'),
    'Current Accrued Expenses': ('current_accrued_expenses', '유동 미지급비용'),
    'Short Term Debt': ('short_term_debt', '단기부채'),
    'Current Debt': ('short_term_debt', '단기부채'),
    'Commercial Paper': ('commercial_paper', '기업어음'),
    'Current Deferred Revenue': ('current_deferred_revenue', '유동 이연수익'),
    'Total Non Current Liabilities Net Minority Interest': ('non_current_liabilities', '비유동부채'),
    'Long Term Debt': ('long_term_debt', '장기부채'),
    'Long Term Debt And Capital Lease Obligation': ('long_term_debt', '장기부채'),
    'Total Debt': ('total_debt', '총 부채'),
    'Net Debt': ('net_debt', '순부채'),
    'Total Equity Gross Minority Interest': ('total_equity', '총 자본'),
    'Stockholders Equity': ('total_equity', '총 자본'),
    'Common Stock Equity': ('common_stock_equity', '보통주 자본'),
    'Common Stock': ('common_stock', '자본금'),
    'Capital Stock': ('capital_stock', '자본금'),
    'Additional Paid In Capital': ('additional_paid_in_capital', '자본잉여금'),
    'Retained Earnings': ('retained_earnings', '이익잉여금'),
    'Gains Losses Not Affecting Retained Earnings': ('other_comprehensive_income', '기타포괄손익'),
    'Other Equity Adjustments': ('other_equity_adjustments', '기타자본조정'),
    'Treasury Stock': ('treasury_stock', '자기주식'),
    'Total Capitalization': ('total_capitalization', '총자본조달액'),
    'Invested Capital': ('invested_capital', '투하자본'),
    'Tangible Book Value': ('tangible_book_value', '유형자산 장부금액'),
    'Working Capital': ('working_capital', '운전자본'),

    # --- 현금흐름표 (Cash Flow) & 기타 ---
    'Operating Cash Flow': ('operating_cash_flow', '영업활동 현금흐름'),
    'Cash Flow From Continuing Operating Activities': ('operating_cash_flow', '영업활동 현금흐름'),
    'Depreciation And Amortization': ('depreciation_and_amortization', '감가상각비'),
    'Depreciation': ('depreciation', '유형자산 감가상각비'),
    'Amortization': ('amortization', '무형자산 상각비'),
    'Amortization Cash Flow': ('amortization', '무형자산 상각비'),
    'Reconciled Depreciation': ('reconciled_depreciation', '조정 감가상각비'),
    'Change In Working Capital': ('change_in_working_capital', '운전자본 증감'),
    'Change In Receivables': ('change_in_receivables', '매출채권 증감'),
    'Changes In Account Receivables': ('change_in_receivables', '매출채권 증감'),
    'Change In Inventory': ('change_in_inventory', '재고자산 증감'),
    'Change In Payable': ('change_in_payables', '매입채무 증감'),
    'Change In Account Payable': ('change_in_payables', '매입채무 증감'),
    'Change In Payables And Accrued Expense': ('change_in_payables_accrued_expense', '매입채무및미지급비용 증감'),
    'Stock Based Compensation': ('stock_based_compensation', '주식보상비용'),
    'Investing Cash Flow': ('investing_cash_flow', '투자활동 현금흐름'),
    'Cash Flow From Continuing Investing Activities': ('investing_cash_flow', '투자활동 현금흐름'),
    'Capital Expenditure': ('capital_expenditure', '자본적 지출 (CAPEX)'),
    'Capital Expenditure Reported': ('capital_expenditure', '자본적 지출 (CAPEX)'),
    'Net PPE Purchase And Sale': ('net_ppe_purchase_sale', '유형자산 순매입/매각'),
    'Purchase Of PPE': ('purchase_of_ppe', '유형자산 매입'),
    'Sale Of PPE': ('sale_of_ppe', '유형자산 매각'),
    'Purchase Of Investment': ('purchase_of_investment', '투자자산 매입'),
    'Sale Of Investment': ('sale_of_investment', '투자자산 매각'),
    'Purchase Of Intangibles': ('purchase_of_intangibles', '무형자산 매입'),
    'Sale Of Intangibles': ('sale_of_intangibles', '무형자산 매각'),
    'Financing Cash Flow': ('financing_cash_flow', '재무활동 현금흐름'),
    'Cash Flow From Continuing Financing Activities': ('financing_cash_flow', '재무활동 현금흐름'),
    'Net Common Stock Issuance': ('net_common_stock_issuance', '보통주 순발행'),
    'Common Stock Issuance': ('common_stock_issuance', '보통주 발행'),
    'Repurchase Of Capital Stock': ('stock_repurchase', '자사주 매입'),
    'Net Issuance Payments Of Debt': ('net_debt_issuance_payment', '부채 순발행/상환'),
    'Repayment Of Debt': ('repayment_of_debt', '부채 상환'),
    'Short Term Debt Payments': ('short_term_debt_payments', '단기부채 상환'),
    'Long Term Debt Payments': ('long_term_debt_payments', '장기부채 상환'),
    'Common Stock Dividend Paid': ('dividend_paid', '배당금 지급'),
    'Cash Dividends Paid': ('dividend_paid', '배당금 지급'),
    'Dividend Paid Cfo': ('dividend_paid_cfo', '배당금 지급(영업활동)'),
    'Preferred Stock Dividend Paid': ('preferred_dividend_paid', '우선주 배당금 지급'),
    'Free Cash Flow': ('free_cash_flow', '잉여현금흐름 (FCF)'),
    'Beginning Cash Position': ('beginning_cash', '기초 현금'),
    'End Cash Position': ('end_cash', '기말 현금'),
    'Changes In Cash': ('net_change_in_cash', '현금 순증감'),
    'Accrued Interest Receivable': {'key': 'accrued_interest_receivable', 'label': '미수이자'},
    'Amortization Of Intangibles': {'key': 'amortization_of_intangibles', 'label': '무형자산상각'},
    'Amortization Of Securities': {'key': 'amortization_of_securities', 'label': '유가증권상각'},
    'Asset Impairment Charge': {'key': 'asset_impairment_charge', 'label': '자산손상차손'},
    'Average Dilution Earnings': {'key': 'average_dilution_earnings', 'label': '평균 희석이익'},
    'Capital Lease Obligations': {'key': 'capital_lease_obligations', 'label': '금융리스부채'},
    'Cash Financial': {'key': 'cash_financial', 'label': '재무현금'},
    'Cash Flow From Discontinued Operation': {'key': 'cash_flow_discontinued_ops', 'label': '중단사업 현금흐름'},
    'Cash From Discontinued Financing Activities': {'key': 'cash_from_discontinued_financing', 'label': '중단사업 재무활동 현금'},
    'Cash From Discontinued Investing Activities': {'key': 'cash_from_discontinued_investing', 'label': '중단사업 투자활동 현금'},
    'Cash From Discontinued Operating Activities': {'key': 'cash_from_discontinued_operating', 'label': '중단사업 영업활동 현금'},
    'Change In Accrued Expense': {'key': 'change_in_accrued_expense', 'label': '미지급비용 증감'},
    'Change In Dividend Payable': {'key': 'change_in_dividend_payable', 'label': '미지급배당금 증감'},
    'Change In Income Tax Payable': {'key': 'change_in_income_tax_payable', 'label': '미지급법인세 증감'},
    'Change In Interest Payable': {'key': 'change_in_interest_payable', 'label': '미지급이자 증감'},
    'Change In Other Current Assets': {'key': 'change_in_other_current_assets', 'label': '기타유동자산 증감'},
    'Change In Other Current Liabilities': {'key': 'change_in_other_current_liabilities', 'label': '기타유동부채 증감'},
    'Change In Other Working Capital': {'key': 'change_in_other_working_capital', 'label': '기타운전자본 증감'},
    'Change In Prepaid Assets': {'key': 'change_in_prepaid_assets', 'label': '선급자산 증감'},
    'Change In Tax Payable': {'key': 'change_in_tax_payable', 'label': '미지급세금 증감'},
    'Classesof Cash Payments': {'key': 'classes_of_cash_payments', 'label': '현금지출 분류'},
    'Classesof Cash Receiptsfrom Operating Activities': {'key': 'classes_of_cash_receipts_operating', 'label': '영업활동 현금수령 분류'},
    'Common Stock Payments': {'key': 'common_stock_payments', 'label': '보통주 지급'},
    'Current Deferred Liabilities': {'key': 'current_deferred_liabilities', 'label': '유동이연부채'},
    'Deferred Income Tax': {'key': 'deferred_income_tax', 'label': '이연법인세'},
    'Deferred Tax': {'key': 'deferred_tax', 'label': '이연세금'},
    'Defined Pension Benefit': {'key': 'defined_pension_benefit', 'label': '확정급여형 퇴직연금'},
    'Depletion Income Statement': {'key': 'depletion_is', 'label': '감모상각비 (손익계산서)'},
    'Depreciation Amortization Depletion': {'key': 'depreciation_amortization_depletion', 'label': '감가상각 및 감모상각비'},
    'Derivative Product Liabilities': {'key': 'derivative_product_liabilities', 'label': '파생상품부채'},
    'Dividends Payable': {'key': 'dividends_payable', 'label': '미지급배당금'},
    'Duefrom Related Parties Current': {'key': 'due_from_related_parties_current', 'label': '유동 특수관계자 미수금'},
    'Duefrom Related Parties Non Current': {'key': 'due_from_related_parties_non_current', 'label': '비유동 특수관계자 미수금'},
    'Dueto Related Parties Current': {'key': 'due_to_related_parties_current', 'label': '유동 특수관계자 미지급금'},
    'Dueto Related Parties Non Current': {'key': 'due_to_related_parties_non_current', 'label': '비유동 특수관계자 미지급금'},
    'Employee Benefits': {'key': 'employee_benefits', 'label': '종업원급여'},
    'Excise Taxes': {'key': 'excise_taxes', 'label': '소비세'},
    'Fixed Assets Revaluation Reserve': {'key': 'fixed_assets_revaluation_reserve', 'label': '고정자산 재평가적립금'},
    'Foreign Currency Translation Adjustments': {'key': 'foreign_currency_translation_adj', 'label': '외화환산조정'},
    'Gain Loss On Sale Of PPE': {'key': 'gain_loss_on_sale_ppe', 'label': '유형자산 처분손익'},
    'Gain On Sale Of Ppe': {'key': 'gain_loss_on_sale_ppe', 'label': '유형자산 처분손익'},
    'Gain On Sale Of Security': {'key': 'gain_on_sale_of_security', 'label': '유가증권 처분이익'},
    'General Partnership Capital': {'key': 'general_partnership_capital', 'label': '일반조합 자본금'},
    'Hedging Assets Current': {'key': 'hedging_assets_current', 'label': '유동 위험회피자산'},
    'Impairment Of Capital Assets': {'key': 'impairment_of_capital_assets', 'label': '자본자산 손상'},
    'Income Tax Payable': {'key': 'income_tax_payable', 'label': '미지급법인세'},
    'Insurance And Claims': {'key': 'insurance_and_claims', 'label': '보험 및 청구'},
    'Interest Paid Cfo': {'key': 'interest_paid_cfo', 'label': '이자 지급 (영업활동)'},
    'Interest Paid Supplemental Data': {'key': 'interest_paid_supplemental', 'label': '이자 지급 (보충자료)'},
    'Interest Payable': {'key': 'interest_payable', 'label': '미지급이자'},
    'Interest Received Cfi': {'key': 'interest_received_investing', 'label': '이자 수령 (투자활동)'},
    'Interest Received Cfo': {'key': 'interest_received_operating', 'label': '이자 수령 (영업활동)'},
    'Interest Received Direct': {'key': 'interest_received', 'label': '이자 수령'},
    'Investment Properties': {'key': 'investment_properties', 'label': '투자부동산'},
    'Investmentsin Joint Venturesat Cost': {'key': 'investments_in_joint_ventures', 'label': '공동기업 투자'},
    'Liabilities Heldfor Sale Non Current': {'key': 'liabilities_held_for_sale_non_current', 'label': '매각예정비유동부채'},
    'Limited Partnership Capital': {'key': 'limited_partnership_capital', 'label': '유한조합 자본금'},
    'Long Term Capital Lease Obligation': {'key': 'long_term_capital_lease_obligation', 'label': '장기금융리스부채'},
    'Loss Adjustment Expense': {'key': 'loss_adjustment_expense', 'label': '손실조정비용'},
    'Minimum Pension Liabilities': {'key': 'minimum_pension_liabilities', 'label': '최소퇴직연금부채'},
    'Minority Interests': {'key': 'minority_interests', 'label': '비지배지분'},
    'Net Foreign Currency Exchange Gain Loss': {'key': 'net_foreign_currency_gain_loss', 'label': '외환순손익'},
    'Net Income From Tax Loss Carryforward': {'key': 'net_income_from_tax_loss_carryforward', 'label': '세무상결손금 이월순이익'},
    'Net Investment Properties Purchase And Sale': {'key': 'net_investment_properties_purchase_sale', 'label': '투자부동산 순매입/매각'},
    'Net Other Financing Charges': {'key': 'net_other_financing_charges', 'label': '순기타재무비용'},
    'Net Other Investing Changes': {'key': 'net_other_investing_changes', 'label': '순기타투자변동'},
    'Net Policyholder Benefits And Claims': {'key': 'net_policyholder_benefits_claims', 'label': '순보험계약자혜택 및 청구'},
    'Net Short Term Debt Issuance': {'key': 'net_short_term_debt_issuance', 'label': '단기부채 순발행액'},
    'Non Current Accounts Receivable': {'key': 'non_current_accounts_receivable', 'label': '비유동매출채권'},
    'Non Current Accrued Expenses': {'key': 'non_current_accrued_expenses', 'label': '비유동미지급비용'},
    'Non Current Deferred Liabilities': {'key': 'non_current_deferred_liabilities', 'label': '비유동이연부채'},
    'Non Current Deferred Revenue': {'key': 'non_current_deferred_revenue', 'label': '비유동이연수익'},
    'Non Current Deferred Taxes Liabilities': {'key': 'non_current_deferred_tax_liabilities', 'label': '비유동이연법인세부채'},
    'Non Current Note Receivables': {'key': 'non_current_note_receivables', 'label': '비유동받을어음'},
    'Non Current Pension And Other Postretirement Benefit Plans': {'key': 'non_current_pension_benefits', 'label': '비유동 퇴직연금 및 기타 퇴직후급여'},
    'Non Current Prepaid Assets': {'key': 'non_current_prepaid_assets', 'label': '비유동선급자산'},
    'Occupancy And Equipment': {'key': 'occupancy_and_equipment', 'label': '점유 및 장비 비용'},
    'Other Cash Adjustment Outside Changein Cash': {'key': 'other_cash_adjustment_outside', 'label': '기타 현금 조정 (외부)'},
    'Other Cash Paymentsfrom Operating Activities': {'key': 'other_cash_payments_operating', 'label': '기타 영업활동 현금지출'},
    'Other Cash Receiptsfrom Operating Activities': {'key': 'other_cash_receipts_operating', 'label': '기타 영업활동 현금수령'},
    'Other Current Assets': {'key': 'other_current_assets', 'label': '기타유동자산'},
    'Other Equity Interest': {'key': 'other_equity_interest', 'label': '기타지분'},
    'Other Non Cash Items': {'key': 'other_non_cash_items', 'label': '기타비현금항목'},
    'Other Non Current Assets': {'key': 'other_non_current_assets', 'label': '기타비유동자산'},
    'Other Non Current Liabilities': {'key': 'other_non_current_liabilities', 'label': '기타비유동부채'},
    'Other Non Interest Expense': {'key': 'other_non_interest_expense', 'label': '기타비이자비용'},
    'Other Payable': {'key': 'other_payable', 'label': '기타미지급금'},
    'Other Properties': {'key': 'other_properties', 'label': '기타부동산'},
    'Other Taxes': {'key': 'other_taxes', 'label': '기타세금'},
    'Otherunder Preferred Stock Dividend': {'key': 'other_under_preferred_dividend', 'label': '기타 우선주 배당금 관련'},
    'Paymentsto Suppliersfor Goodsand Services': {'key': 'payments_to_suppliers', 'label': '공급업체 대금지급'},
    'Pension And Employee Benefit Expense': {'key': 'pension_employee_benefit_expense', 'label': '퇴직연금 및 종업원급여 비용'},
    'Pensionand Other Post Retirement Benefit Plans Current': {'key': 'current_pension_benefits', 'label': '유동 퇴직연금 및 기타 퇴직후급여'},
    'Policyholder Benefits Ceded': {'key': 'policyholder_benefits_ceded', 'label': '출재보험 계약자혜택'},
    'Policyholder Benefits Gross': {'key': 'policyholder_benefits_gross', 'label': '총 보험계약자혜택'},
    'Preferred Securities Outside Stock Equity': {'key': 'preferred_securities_outside_equity', 'label': '자본 외 우선증권'},
    'Preferred Stock': {'key': 'preferred_stock', 'label': '우선주'},
    'Preferred Stock Dividends': {'key': 'preferred_stock_dividends', 'label': '우선주 배당금'},
    'Preferred Stock Equity': {'key': 'preferred_stock_equity', 'label': '우선주 자본'},
    'Preferred Stock Issuance': {'key': 'preferred_stock_issuance', 'label': '우선주 발행'},
    'Preferred Stock Payments': {'key': 'preferred_stock_payments', 'label': '우선주 지급'},
    'Proceeds From Stock Option Exercised': {'key': 'proceeds_from_stock_options', 'label': '스톡옵션 행사 수익'},
    'Purchase Of Investment Properties': {'key': 'purchase_of_investment_properties', 'label': '투자부동산 매입'},
    'Receiptsfrom Customers': {'key': 'receipts_from_customers', 'label': '고객으로부터의 수령액'},
    'Receivables Adjustments Allowances': {'key': 'receivables_adjustments_allowances', 'label': '매출채권 조정 및 충당금'},
    'Rent And Landing Fees': {'key': 'rent_and_landing_fees', 'label': '임차료 및 착륙료'},
    'Restricted Common Stock': {'key': 'restricted_common_stock', 'label': '제한조건부 보통주'},
    'Salaries And Wages': {'key': 'salaries_and_wages', 'label': '급여 및 임금'},
    'Sale Of Investment Properties': {'key': 'sale_of_investment_properties', 'label': '투자부동산 매각'},
    'Securities Amortization': {'key': 'securities_amortization', 'label': '유가증권상각'},
    'Taxes Receivable': {'key': 'taxes_receivable', 'label': '미수세금'},
    'Taxes Refund Paid': {'key': 'taxes_refund_paid', 'label': '세금 환급 지급'},
    'Taxes Refund Paid Direct': {'key': 'taxes_refund_paid', 'label': '세금 환급 지급'},
    'Total Other Finance Cost': {'key': 'total_other_finance_cost', 'label': '총기타재무원가'},
    'Total Partnership Capital': {'key': 'total_partnership_capital', 'label': '총조합 자본금'},
    'Total Tax Payable': {'key': 'total_tax_payable', 'label': '총미지급세금'},
    'Tradeand Other Payables Non Current': {'key': 'trade_other_payables_non_current', 'label': '비유동 매입채무 및 기타미지급금'},
    'Treasury Shares Number': {'key': 'treasury_shares_number', 'label': '자기주식 주식수'},
    'Unrealized Gain Loss': {'key': 'unrealized_gain_loss', 'label': '미실현손익'},
    'Unrealized Gain Loss On Investment Securities': {'key': 'unrealized_gain_loss_investment_securities', 'label': '투자증권 미실현손익'},
        'Restricted Common Stock': ('restricted_common_stock', '제한의결권부 보통주'),
    'Receiptsfrom Customers': ('receipts_from_customers', '고객으로부터의 현금유입'),
    'Duefrom Related Parties Non Current': ('due_from_related_parties_non_current', '비유동성 관계사 대여금'),
    'Other Current Assets': ('other_current_assets', '기타 유동자산'),
    'Defined Pension Benefit': ('defined_pension_benefit', '확정급여부채'),
    'Policyholder Benefits Ceded': ('policyholder_benefits_ceded', '출재보험금'),
    'Cash From Discontinued Financing Activities': ('cash_from_discontinued_financing_activities', '중단사업금융활동현금흐름'),
    'Minimum Pension Liabilities': ('minimum_pension_liabilities', '최소연금부채'),
    'Preferred Securities Outside Stock Equity': ('preferred_securities_outside_stock_equity', '자본성증권'),
    'General Partnership Capital': ('general_partnership_capital', '합명회사자본'),
    'Policyholder Benefits Gross': ('policyholder_benefits_gross', '보유보험금'),
    'Net Policyholder Benefits And Claims': ('net_policyholder_benefits_and_claims', '순보험금'),
    'Common Stock Payments': ('common_stock_payments', '보통주지급'),
    'Dueto Related Parties Non Current': ('due_to_related_parties_non_current', '비유동성 관계사 차입금'),
    'Loss Adjustment Expense': ('loss_adjustment_expense', '손해사정비'),
    'Preferred Stock Payments': ('preferred_stock_payments', '우선주지급'),
    'Non Current Note Receivables': ('non_current_note_receivables', '비유동성 받을어음'),
    'Duefrom Related Parties Current': ('due_from_related_parties_current', '유동성 관계사 대여금'),
    'Change In Other Current Liabilities': ('change_in_other_current_liabilities', '기타유동부채의 증감'),
    'Total Partnership Capital': ('total_partnership_capital', '총파트너쉽자본'),
    'Current Deferred Liabilities': ('current_deferred_liabilities', '유동이연부채'),
    'Liabilities Heldfor Sale Non Current': ('liabilities_held_for_sale_non_current', '비유동매각예정부채'),
    'Interest Paid Cfo': ('interest_paid_cfo', '이자지급액(영업)'),
    'Non Current Accrued Expenses': ('non_current_accrued_expenses', '비유동성 미지급비용'),
    'Unrealized Gain Loss On Investment Securities': ('unrealized_gain_loss_on_investment_securities', '투자증권미실현손익'),
    'Otherunder Preferred Stock Dividend': ('other_under_preferred_stock_dividend', '기타우선주배당금'),
    'Average Dilution Earnings': ('average_dilution_earnings', '평균희석이익'),
    'Other Cash Paymentsfrom Operating Activities': ('other_cash_payments_from_operating_activities', '기타영업활동현금지출'),
    'Derivative Product Liabilities': ('derivative_product_liabilities', '파생상품부채'),
    'Net Investment Properties Purchase And Sale': ('net_investment_properties_purchase_and_sale', '투자부동산순매매액'),
    'Gain Loss On Sale Of PPE': ('gain_loss_on_sale_of_ppe', '유형자산처분손익'),
    'Gain On Sale Of Ppe': ('gain_on_sale_of_ppe', '유형자산처분이익'),
    'Receivables Adjustments Allowances': ('receivables_adjustments_allowances', '수취채권조정충당금'),
    'Investment Properties': ('investment_properties', '투자부동산'),
    'Amortization Of Securities': ('amortization_of_securities', '유가증권상각'),
    'Classesof Cash Receiptsfrom Operating Activities': ('classes_of_cash_receipts_from_operating_activities', '영업활동현금흐름종류'),
    'Asset Impairment Charge': ('asset_impairment_charge', '자산손상차손'),
    'Gain On Sale Of Security': ('gain_on_sale_of_security', '유가증권처분이익'),
    'Other Non Current Liabilities': ('other_non_current_liabilities', '기타 비유동부채'),
    'Cash From Discontinued Investing Activities': ('cash_from_discontinued_investing_activities', '중단사업투자활동현금흐름'),
    'Tradeand Other Payables Non Current': ('trade_and_other_payables_non_current', '비유동성 매입채무 및 기타채무'),
    'Net Foreign Currency Exchange Gain Loss': ('net_foreign_currency_exchange_gain_loss', '외환차손익'),
    'Investmentsin Joint Venturesat Cost': ('investments_in_joint_ventures_at_cost', '관계기업투자(원가법)'),
    'Deferred Income Tax': ('deferred_income_tax', '이연법인세'),
    'Income Tax Payable': ('income_tax_payable', '미지급법인세'),
    'Rent And Landing Fees': ('rent_and_landing_fees', '임차료및착륙료'),
    'Dueto Related Parties Current': ('due_to_related_parties_current', '유동성 관계사 차입금'),
    'Interest Received Cfo': ('interest_received_cfo', '이자수취액(영업)'),
    'Non Current Pension And Other Postretirement Benefit Plans': ('non_current_pension_and_other_postretirement_benefit_plans', '비유동성 퇴직연금 및 기타후생급여'),
    'Interest Received Cfi': ('interest_received_cfi', '이자수취액(투자)'),
    'Change In Income Tax Payable': ('change_in_income_tax_payable', '미지급법인세의 증감'),
    'Non Current Deferred Liabilities': ('non_current_deferred_liabilities', '비유동성 이연부채'),
    'Total Tax Payable': ('total_tax_payable', '총미지급세금'),
    'Pensionand Other Post Retirement Benefit Plans Current': ('pension_and_other_post_retirement_benefit_plans_current', '유동성 퇴직연금 및 기타후생급여'),
    'Proceeds From Stock Option Exercised': ('proceeds_from_stock_option_exercised', '주식매수선택권행사이익'),
    'Change In Prepaid Assets': ('change_in_prepaid_assets', '선급자산의 증감'),
    'Preferred Stock Equity': ('preferred_stock_equity', '우선주자본'),
    'Amortization Of Intangibles': ('amortization_of_intangibles', '무형자산상각'),
    'Depletion Income Statement': ('depletion_income_statement', '감모상각비'),
    'Treasury Shares Number': ('treasury_shares_number', '자기주식수'),
    'Dividends Payable': ('dividends_payable', '미지급배당금'),
    'Cash Flow From Discontinued Operation': ('cash_flow_from_discontinued_operation', '중단사업현금흐름'),
    'Other Non Current Assets': ('other_non_current_assets', '기타 비유동자산'),
    'Hedging Assets Current': ('hedging_assets_current', '유동성 위험회피자산'),
    'Purchase Of Investment Properties': ('purchase_of_investment_properties', '투자부동산매입'),
    'Other Cash Receiptsfrom Operating Activities': ('other_cash_receipts_from_operating_activities', '기타영업활동현금흐름'),
    'Other Taxes': ('other_taxes', '기타세금'),
    'Deferred Tax': ('deferred_tax', '이연법인세'),
    'Fixed Assets Revaluation Reserve': ('fixed_assets_revaluation_reserve', '고정자산재평가적립금'),
    'Preferred Stock': ('preferred_stock', '우선주'),
    'Change In Other Current Assets': ('change_in_other_current_assets', '기타유동자산의 증감'),
    'Minority Interests': ('minority_interests', '소수주주지분'),
    'Other Equity Interest': ('other_equity_interest', '기타지분'),
    'Accrued Interest Receivable': ('accrued_interest_receivable', '미수이자'),
    'Other Cash Adjustment Outside Changein Cash': ('other_cash_adjustment_outside_change_in_cash', '현금변동외기타현금조정'),
    'Pension And Employee Benefit Expense': ('pension_and_employee_benefit_expense', '퇴직급여'),
    'Preferred Stock Dividends': ('preferred_stock_dividends', '우선주배당금'),
    'Change In Accrued Expense': ('change_in_accrued_expense', '미지급비용의 증감'),
    'Impairment Of Capital Assets': ('impairment_of_capital_assets', '자본자산손상'),
    'Classesof Cash Payments': ('classes_of_cash_payments', '현금지급의 종류'),
    'Employee Benefits': ('employee_benefits', '종업원급여'),
    'Unrealized Gain Loss': ('unrealized_gain_loss', '미실현손익'),
    'Cash From Discontinued Operating Activities': ('cash_from_discontinued_operating_activities', '중단사업영업활동현금흐름'),
    'Change In Dividend Payable': ('change_in_dividend_payable', '미지급배당금의 증감'),
    'Net Other Financing Charges': ('net_other_financing_charges', '순기타금융비용'),
    'Capital Lease Obligations': ('capital_lease_obligations', '금융리스부채'),
    'Total Other Finance Cost': ('total_other_finance_cost', '총기타금융비용'),
    'Non Current Deferred Taxes Liabilities': ('non_current_deferred_taxes_liabilities', '비유동성이연법인세부채'),
    'Net Short Term Debt Issuance': ('net_short_term_debt_issuance', '단기차입금순발행'),
    'Non Current Accounts Receivable': ('non_current_accounts_receivable', '비유동성 매출채권'),
    'Paymentsto Suppliersfor Goodsand Services': ('payments_to_suppliers_for_goods_and_services', '공급자에대한현금지출'),
    'Interest Received Direct': ('interest_received_direct', '이자수취액(직접법)'),
    'Other Properties': ('other_properties', '기타부동산'),
    'Taxes Refund Paid': ('taxes_refund_paid', '세금환급'),
    'Insurance And Claims': ('insurance_and_claims', '보험및청구'),
    'Preferred Stock Issuance': ('preferred_stock_issuance', '우선주발행'),
    'Interest Paid Supplemental Data': ('interest_paid_supplemental_data', '이자지급액(보충)'),
    'Securities Amortization': ('securities_amortization', '유가증권상각'),
    'Foreign Currency Translation Adjustments': ('foreign_currency_translation_adjustments', '외화환산조정'),
    'Net Other Investing Changes': ('net_other_investing_changes', '순기타투자변동'),
    'Other Non Interest Expense': ('other_non_interest_expense', '기타비이자비용'),
    'Non Current Deferred Revenue': ('non_current_deferred_revenue', '비유동성이연수익'),
    'Sale Of Investment Properties': ('sale_of_investment_properties', '투자부동산매각'),
    'Other Payable': ('other_payable', '기타미지급금'),
    'Taxes Receivable': ('taxes_receivable', '미수세금'),
    'Depreciation Amortization Depletion': ('depreciation_amortization_depletion', '감가상각비'),
    'Change In Tax Payable': ('change_in_tax_payable', '미지급세금의 증감'),
    'Occupancy And Equipment': ('occupancy_and_equipment', '점유및장비'),
    'Net Income From Tax Loss Carryforward': ('net_income_from_tax_loss_carryforward', '이월결손금으로인한순이익'),
    'Cash Financial': ('cash_financial', '재무활동현금'),
    'Limited Partnership Capital': ('limited_partnership_capital', '합자회사자본'),
    'Long Term Capital Lease Obligation': ('long_term_capital_lease_obligation', '장기금융리스부채'),
    'Interest Payable': ('interest_payable', '미지급이자'),
    'Taxes Refund Paid Direct': ('taxes_refund_paid_direct', '세금환급(직접법)'),
    'Salaries And Wages': ('salaries_and_wages', '급여'),
    'Non Current Prepaid Assets': ('non_current_prepaid_assets', '비유동성 선급자산'),
    'Change In Other Working Capital': ('change_in_other_working_capital', '기타운전자본의 증감'),
    'Change In Interest Payable': ('change_in_interest_payable', '미지급이자의 증감'),
    'Other Non Cash Items': ('other_non_cash_items', '기타비현금항목'),
}

def populate_financial_items(apps, schema_editor):
    """
    FINANCIAL_ITEMS_DATA에 정의된 데이터로 FinancialItem 모델을 생성하거나 업데이트합니다.
    """
    FinancialItem = apps.get_model('stocks', 'FinancialItem')
    
    updated_count = 0
    created_count = 0

    for yfinance_name, (standard_key, korean_label) in FINANCIAL_ITEMS_DATA.items():
        defaults = {
            'standard_key': standard_key,
            'korean_label': korean_label,
            'is_active': True
        }
        
        obj, created = FinancialItem.objects.update_or_create(
            yfinance_name=yfinance_name,
            defaults=defaults
        )

        if created:
            created_count += 1
        else:
            updated_count += 1

    print(f"\nMigration complete. Created: {created_count}, Updated: {updated_count}")

def reverse_code(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        # ⚠️ 여러분의 실제 이전 마이그레이션 파일명으로 변경해야 합니다!
        ('stocks', '0002_dailymarketreport_stockdailyanalysis'), 
    ]

    operations = [
        migrations.RunPython(populate_financial_items, reverse_code),
    ]