# Generated by Django 5.2.5 on 2025-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_populate_financial_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change_percent',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='변동률 (%)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='종목코드'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend_yield',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='배당수익률 (%)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='forward_eps',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='EPS (Forward)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='forward_pe',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='PER (Forward)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='산업'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='long_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='종목명 (전체)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_to_book',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='PBR'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trailing_eps',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='EPS (Trailing)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trailing_pe',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='PER (Trailing)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='거래량'),
        ),
    ]
