# Generated by Django 5.2.5 on 2025-08-13 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_change_percent_alter_stock_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('adj_close', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'Stock Price Histories',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_date')],
            },
        ),
    ]
