# Generated by Django 5.2.5 on 2025-08-13 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stockpricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.BigIntegerField()),
                ('period_type', models.CharField(choices=[('A', 'Annual'), ('Q', 'Quarterly')], max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='stocks.financialitem')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'item', 'date', 'period_type'), name='unique_financial_statement')],
            },
        ),
    ]
