# Generated by Django 5.2.5 on 2025-08-14 04:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_financialstatement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-market_cap'], 'verbose_name': '주식 정보', 'verbose_name_plural': '주식 정보 목록'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='city',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='state',
        ),
        migrations.AddField(
            model_name='stock',
            name='beta',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='베타 (시장 민감도)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='통화 (e.g., USD, KRW)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='earnings_growth',
            field=models.FloatField(blank=True, null=True, verbose_name='이익 성장률 (YoY)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='enterprise_to_ebitda',
            field=models.FloatField(blank=True, null=True, verbose_name='EV/EBITDA'),
        ),
        migrations.AddField(
            model_name='stock',
            name='enterprise_value',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='기업가치 (EV)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='fifty_day_average',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='50일 이동평균'),
        ),
        migrations.AddField(
            model_name='stock',
            name='held_percent_insiders',
            field=models.FloatField(blank=True, null=True, verbose_name='내부자 지분율 (%)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='held_percent_institutions',
            field=models.FloatField(blank=True, null=True, verbose_name='기관 지분율 (%)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='number_of_analyst_opinions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='애널리스트 수'),
        ),
        migrations.AddField(
            model_name='stock',
            name='overall_risk',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='종합 리스크 점수'),
        ),
        migrations.AddField(
            model_name='stock',
            name='payout_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='배당성향 (%)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='전일 종가'),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_to_sales',
            field=models.FloatField(blank=True, null=True, verbose_name='PSR (TTM)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='recommendation_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='종합 투자의견 (e.g., buy, hold)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='return_on_equity',
            field=models.FloatField(blank=True, null=True, verbose_name='자기자본이익률 (ROE)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='revenue_growth',
            field=models.FloatField(blank=True, null=True, verbose_name='매출 성장률 (YoY)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='shares_outstanding',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='발행주식수'),
        ),
        migrations.AddField(
            model_name='stock',
            name='short_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='공매도 비율 (Short Ratio)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='target_high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='최고 목표주가'),
        ),
        migrations.AddField(
            model_name='stock',
            name='target_low_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='최저 목표주가'),
        ),
        migrations.AddField(
            model_name='stock',
            name='target_mean_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='평균 목표주가'),
        ),
        migrations.AddField(
            model_name='stock',
            name='two_hundred_day_average',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='200일 이동평균'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='마지막 동기화 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='시장 (e.g., NMS, KOSPI)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trailing_eps',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='EPS (TTM)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trailing_pe',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='PER (TTM)'),
        ),
        migrations.CreateModel(
            name='CompanyOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='직책')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='나이')),
                ('total_pay', models.BigIntegerField(blank=True, null=True, verbose_name='총 보수')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='stocks.stock', verbose_name='주식')),
            ],
            options={
                'verbose_name': '기업 임원',
                'verbose_name_plural': '기업 임원 목록',
                'unique_together': {('stock', 'name')},
            },
        ),
    ]
