# Generated by Django 5.2.5 on 2025-08-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stock_options_remove_stock_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialitem',
            options={'ordering': ['statement_type', 'order']},
        ),
        migrations.AddField(
            model_name='financialitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='재무제표 내 표시 순서'),
        ),
        migrations.AddField(
            model_name='financialitem',
            name='statement_type',
            field=models.CharField(blank=True, choices=[('IS', 'Income Statement'), ('BS', 'Balance Sheet'), ('CF', 'Cash Flow Statement')], help_text='이 계정과목이 속한 재무제표의 종류', max_length=2, null=True),
        ),
    ]
