# Generated by Django 5.2.5 on 2025-08-16 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_financialitem_options_financialitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryFinancialAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(db_index=True, max_length=100)),
                ('period_type', models.CharField(choices=[('A', 'Annual'), ('Q', 'Quarterly')], max_length=1)),
                ('average_values', models.JSONField(default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.financialitem')),
            ],
            options={
                'verbose_name': '산업별 재무 평균',
                'verbose_name_plural': '산업별 재무 평균',
                'unique_together': {('industry', 'item', 'period_type')},
            },
        ),
    ]
