# Generated by Django 5.2.5 on 2025-08-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_industryfinancialaverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='indicators', serialize=False, to='stocks.stockpricehistory')),
                ('sma_20', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='20일 단순이동평균')),
                ('sma_60', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='60일 단순이동평균')),
                ('sma_120', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='120일 단순이동평균')),
                ('ema_20', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='20일 지수이동평균')),
                ('ema_60', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='60일 지수이동평균')),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RSI (14일)')),
                ('macd', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='MACD')),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='MACD Signal Line')),
                ('macd_hist', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='MACD Histogram')),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='볼린저밴드 상단')),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='볼린저밴드 중간')),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='볼린저밴드 하단')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
