# Generated by Django 5.2.5 on 2025-09-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_technicalindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='SAC_v1', max_length=50, verbose_name='사용 모델')),
                ('prediction_date', models.DateField(verbose_name='예측 기준일')),
                ('predicted_signal', models.CharField(max_length=50, verbose_name='예측 시그널')),
                ('predicted_ratio', models.FloatField(verbose_name='예측 비율')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시간')),
                ('actual_outcome', models.CharField(blank=True, max_length=20, null=True, verbose_name='실제 결과')),
                ('actual_change_percent', models.FloatField(blank=True, null=True, verbose_name='실제 등락률 (%)')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='예측 성공 여부')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='평가 시간')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_logs', to='stocks.stock', verbose_name='주식')),
            ],
            options={
                'verbose_name': 'AI 예측 로그',
                'verbose_name_plural': 'AI 예측 로그',
                'ordering': ['-prediction_date', 'stock'],
                'unique_together': {('stock', 'prediction_date', 'model_name')},
            },
        ),
    ]
